package com.codebaron.filmworld.models.filmdetails

data class FilmDetailsData(
    val adult: Boolean,
    val backdrop_path: String,
    val belongs_to_collection: BelongsToCollection,
    val budget: Int,
    val genres: List<Genre>,
    val homepage: String,
    val id: Int,
    val imdb_id: String,
    val original_language: String,
    val original_title: String,
    val overview: String,
    val popularity: Double,
    val poster_path: String,
    val production_companies: List<ProductionCompany>,
    val production_countries: List<ProductionCountry>,
    val release_date: String,
    val revenue: Int,
    val runtime: Int,
    val spoken_languages: List<SpokenLanguage>,
    val status: String,
    val tagline: String,
    val title: String,
    val video: Boolean,
    val vote_average: Double,
    val vote_count: Int
)

val dummyFilmDetailsData = FilmDetailsData(
    adult = false,
    backdrop_path = "/ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg",
    belongs_to_collection = dummyBelongsToCollection,
    budget = 200,
    genres = dummyGenre,
    homepage = "https://www.spidermannowayhome.movie",
    id = 20003,
    imdb_id = "tt10872600",
    original_language = "en",
    original_title = "Spider-Man: No Way Home",
    overview = "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity = 2116.822,
    poster_path = "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    production_companies = dummyProductionCompany,
    production_countries = dummyProductionCountry,
    release_date = "2021-12-15",
    revenue = 1892000000,
    runtime = 148,
    spoken_languages = dummySpokenLanguage,
    status = "Released",
    tagline = "The Multiverse unleashed.",
    title = "Spider-Man: No Way Home",
    video = false,
    vote_average = 8.1,
    vote_count = 13925
)